
[target.aarch64-linux-android]
linker = "/nix/store/1iidjzprjnvg2c4c8qkgzy36058fxal0-android-sdk-env/share/android-sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang"

[target.armv7-linux-androideabi]
linker = "/nix/store/1iidjzprjnvg2c4c8qkgzy36058fxal0-android-sdk-env/share/android-sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang"

[target.x86_64-linux-android]
linker="/nix/store/1iidjzprjnvg2c4c8qkgzy36058fxal0-android-sdk-env/share/android-sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android24-clang"

[target.i686-linux-android]
linker="/nix/store/1iidjzprjnvg2c4c8qkgzy36058fxal0-android-sdk-env/share/android-sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android24-clang"

