on:
  push:
    #tags:
      #- "*"

name: Release

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: nix shell
        run: nix develop -L --verbose

      - name: build asleh
        run: |
          nix develop -c bash -c '
            set -e
            cd asleh-rs
            cargo build --lib \
              --target x86_64-linux-android \
              --target i686-linux-android \
              --target armv7-linux-androideabi \
              --target aarch64-linux-android
          '

      - name: build jniLibs
        run: |
          cd asleh-rs
          mkdir -p jniLibs/arm64-v8a/
          cp target/aarch64-linux-android/debug/libasleh.so jniLibs/arm64-v8a/libuniffi_asleh.so

          mkdir -p jniLibs/armeabi-v7a/
          cp target/armv7-linux-androideabi/debug/libasleh.so jniLibs/armeabi-v7a/libuniffi_asleh.so

          mkdir -p jniLibs/x86/
          cp target/i686-linux-android/debug/libasleh.so jniLibs/x86/libuniffi_asleh.so

          mkdir -p jniLibs/x86_64/
          cp target/x86_64-linux-android/debug/libasleh.so jniLibs/x86_64/libuniffi_asleh.so

          mv jniLibs ../app/src/main/

      - name: generate kotlin bindings
        run: |
          nix develop -c bash -c '
            set -e
            cd asleh-rs
            cargo run --features=uniffi/cli \
                      --bin uniffi-bindgen \
                      generate src/asleh.udl \
                      --language kotlin
            mv src/uniffi ../app/src/main/java/
          '

      - name: build android release
        run: |
          nix develop -c bash -c '
            set -e
            chmod +x ./gradlew
            chmod -w local.properties
            ./gradlew assembleRelease
          '

      - name: upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./app/build/outputs/apk/release/app-release.apk

