on:
  push:
    tags:
      - "*"

name: Release

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: nix shell
        run: nix develop -L --verbose

      - name: build asleh
        run: |
          nix develop -c bash -c '
            set -e
            cd asleh-rs
            cargo build --release --no-default-features --lib \
              --target x86_64-linux-android \
              --target i686-linux-android \
              --target armv7-linux-androideabi \
              --target aarch64-linux-android \
              --target aarch64-apple-ios \
              --target x86_64-apple-ios \
              --target aarch64-apple-ios-sim
          '

      - name: build jniLibs
        run: |
          cd asleh-rs
          mkdir -p jniLibs/arm64-v8a/
          cp target/aarch64-linux-android/release/libasleh.so jniLibs/arm64-v8a/libuniffi_asleh.so

          mkdir -p jniLibs/armeabi-v7a/
          cp target/armv7-linux-androideabi/release/libasleh.so jniLibs/armeabi-v7a/libuniffi_asleh.so

          mkdir -p jniLibs/x86/
          cp target/i686-linux-android/release/libasleh.so jniLibs/x86/libuniffi_asleh.so

          mkdir -p jniLibs/x86_64/
          cp target/x86_64-linux-android/release/libasleh.so jniLibs/x86_64/libuniffi_asleh.so

          mv jniLibs ../app/src/main/

      - name: generate kotlin bindings
        run: |
          nix develop -c bash -c '
            set -e
            cd asleh-rs
            cargo run --features=uniffi/cli \
                      --bin uniffi-bindgen \
                      generate src/asleh.udl \
                      --language kotlin
            mv src/uniffi ../app/src/main/java/
          '

      - name: generate swift bindings and build module
        run: |
          nix develop -c bash -c '
            set -e
            cd asleh-rs
            
            # Generate Swift bindings
            mkdir -p src/swift
            cargo run --features=uniffi/cli \
                      --bin uniffi-bindgen \
                      generate src/asleh.udl \
                      --language swift \
                      --out-dir src/swift
            
            mv src/swift/aslehFFI.modulemap src/swift/module.modulemap
            
            SDK_PATH=$(xcrun --show-sdk-path --sdk iphoneos)
            mkdir -p build/swift/aarch64-apple-ios
            swiftc \
                -module-name asleh \
                -emit-library -o build/swift/aarch64-apple-ios/libasleh.dylib \
                -emit-module -emit-module-path build/swift/aarch64-apple-ios \
                -parse-as-library \
                -target arm64-apple-ios11.0 \
                -sdk $SDK_PATH \
                -L target/aarch64-apple-ios/release \
                -lasleh \
                -Xcc -fmodule-map-file=src/swift/module.modulemap \
                src/swift/asleh.swift
            

            mkdir -p ../iosApp/Shared
            cp src/swift/asleh.swift ../iosApp/Shared/
            cp src/swift/aslehFFI.h ../iosApp/Shared/
            cp src/swift/module.modulemap ../iosApp/Shared/
            cp -r build/swift/aarch64-apple-ios/* ../iosApp/Shared/
            cp target/aarch64-apple-ios/release/libasleh.a ../iosApp/Shared/
          '

      - name: generate release key
        run: |
          cd app/ && echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > key.jks

      - name: build android release
        env: 
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          nix develop -c bash -c '
            set -e
            chmod +x ./gradlew
            chmod -w local.properties
            ./gradlew assembleRelease
          '

      - name: upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./app/build/outputs/apk/release/app-release.apk

